version: "3.8"

services:
  development_app:
    build:
      context: .
      dockerfile: Dockerfile.development
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://postgres:123456789@database:5432/rinha
    volumes:
      - .:/app
      - ../db_scripts:/app/migrations
    depends_on:
      - database
    ports:
      - "8080:8080"
  database:
      image: postgres:16
      hostname: database
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123456789
        POSTGRES_DB: rinha
      ports:
        - "5432:5432"
      volumes:
        - ../db_scripts:/docker-entrypoint-initdb.d:ro